name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull imbulana/mlem:latest
    - name: Delete Old docker container
      run: sudo docker rm -f mlem-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name mlem-container imbulana/mlem